command: ["python3", "app.py"]

env:
  - name: DATABRICKS_SQL_WAREHOUSE_ID
    valueFrom:
      secretRef:
        scope: cga-app-config
        key: sql_warehouse_id
  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom:
      secretRef:
        scope: cga-app-config
        key: genie_space_id
  - name: COINGECKO_CATALOG
    value: "cgadev"
